### Merge script

In [38]:
import pandas as pd

In [39]:
iSUPER = pd.read_csv("Filtered dataset/isuper_5min_full.csv")
Weather_underground  = pd.read_csv("Filtered dataset/Weather_Underground_5min_East_Boston_full.csv")

In [40]:
iSUPER["timestamp_utc"] = pd.to_datetime(iSUPER["timestamp_utc"], utc=True)
Weather_underground["timestamp_utc"]  = pd.to_datetime(Weather_underground["timestamp_utc"],  utc=True)

In [41]:
iSUPER = iSUPER.sort_values("timestamp_utc")
Weather_underground  = Weather_underground.sort_values("timestamp_utc")

display(iSUPER.head(), Weather_underground.head())

              timestamp_utc  rh_sensor  temp_sensor      pm1     pm25     pm10
0 2025-08-17 00:00:00+00:00      48.76        27.10  14.3818  14.5094  14.5094
1 2025-08-17 00:05:00+00:00      49.02        27.00  13.9388  14.2436  14.2436
2 2025-08-17 00:10:00+00:00      49.20        26.90  13.7452  13.9998  13.9998
3 2025-08-17 00:15:00+00:00      49.40        26.82  13.6772  13.9532  16.2588
4 2025-08-17 00:20:00+00:00      49.50        26.76  12.6036  12.7306  12.7306

,timestamp_utc,Temperature_C,Dew_Point_C,Humidity_%,Speed_kmh,Pressure_hPa,Precip_Rate_mm,Precip_Accum_mm,Wind,Dew/Temp fog?,RH fog?
0,2025-01-01 05:00:00+00:00,6.39,5.11,91.0,5.95,1005.76,0.0,0.0,East,1.0,0.0
1,2025-01-01 05:05:00+00:00,6.50,5.22,91.0,9.01,1006.10,0.0,0.0,East,1.0,0.0
2,2025-01-01 05:10:00+00:00,6.61,5.28,91.0,7.40,1005.76,0.0,0.0,East,1.0,0.0
3,2025-01-01 05:15:00+00:00,6.72,5.39,91.0,7.88,1005.76,0.0,0.0,East,1.0,0.0
4,2025-01-01 05:20:00+00:00,6.78,5.50,91.0,7.24,1005.42,0.0,0.0,ENE,1.0,0.0

In [42]:
df_merged = iSUPER.merge(
    Weather_underground,
    on="timestamp_utc",
    how="inner",
    suffixes=("_che", "_wu")
)

display(df_merged.head()) #df_merged.head()
df_merged.shape

,timestamp_utc,rh_sensor,temp_sensor,pm1,pm25,pm10,Temperature_C,Dew_Point_C,Humidity_%,Speed_kmh,Pressure_hPa,Precip_Rate_mm,Precip_Accum_mm,Wind,Dew/Temp fog?,RH fog?
0,2025-08-17 00:00:00+00:00,48.76,27.10,14.3818,14.5094,14.5094,24.06,17.61,67.0,15.12,1016.59,0.0,0.0,SSW,0.0,0.0
1,2025-08-17 00:05:00+00:00,49.02,27.00,13.9388,14.2436,14.2436,23.89,17.56,68.0,15.45,1016.93,0.0,0.0,SSW,0.0,0.0
2,2025-08-17 00:10:00+00:00,49.20,26.90,13.7452,13.9998,13.9998,23.78,17.72,69.0,15.29,1016.93,0.0,0.0,SSW,0.0,0.0
3,2025-08-17 00:15:00+00:00,49.40,26.82,13.6772,13.9532,16.2588,23.83,17.22,67.0,18.34,1016.93,0.0,0.0,SSW,0.0,0.0
4,2025-08-17 00:20:00+00:00,49.50,26.76,12.6036,12.7306,12.7306,24.06,17.33,66.0,14.32,1016.59,0.0,0.0,SSW,0.0,0.0

(25632, 16)

In [43]:
df_merged.to_csv("Filtered dataset/iSUPER_Weather_Underground_merged_2025.csv", index=False)

### Visualization